### ISSUE TITLE
Support Surface v0.5

### ISSUE THREAD

**Issue by msaraiva** [surface-ui/surface_formatter#20]
Hi @paulstatezny!

Since all syntax changes have been already implemented and the new converter is already available in https://github.com/surface-ui/surface/tree/surface-next, I think we can start working on other important projects that should be released alongside Surface to make sure everything goes as smooth as possible. My plan is to have `v0.5` released by the end on the week unless something unexpected comes up.

Detailed information about the migration process can be found in the [Migration Guide](https://github.com/surface-ui/surface/blob/surface-next/MIGRATING) and the [CHANGELOG](https://github.com/surface-ui/surface/blob/surface-next/CHANGELOG.md#v050-wip) has been updated with all changes.

Regarding the formatter, the most important changes to be aware of are probably:

  * Replace the sigil `~H` with `~F` to avoid conflict with `HEEx`
  * Replace interpolation delimiters `{{` and `}}` with `{` and `}`
  * Support private comments using `{!-- --}`
  * Supporting some expressions at the attributes "area", namely `{ }`, `{... }` and `{= }`
  * The new block expressions: `{#if}..{#elseif}..{#else}..{/if}`, `{#for}..{#else}..{/for}`, etc.

The last three changes above introduces new tokens or metadata at the tokenizer level so we'll have to handle them. For a quick reference, they are: 

  * `{:comment, comment, %{visibility: visibility}}` - where `visibility` can be `:private` or `:public`, representing `{!-- --}` and `<!-- -->` respectively.
  * `{:tagged_expr, marker, expr, meta}` - where `marker` can be `...` or `=`
  * `{:block, name, expr, body, meta}` - where `name` can be the name of the block (e.g. `if`, `case`) or sub-block (e.g. `else`, `match`)

### The new `NodeTranslator` behaviour

We changed the design of the parser allowing external tools to use a different node translator that can generate a tree of nodes according to their needs. All you have to do is implementing the [Surface.Compiler.NodeTranslator](https://github.com/surface-ui/surface/blob/surface-next/lib/surface/compiler/node_translator.ex) behaviour and define the nodes in the shape you want. Here's the implementation of the translator used by the default Surface parser: https://github.com/surface-ui/surface/blob/surface-next/lib/surface/compiler/parse_tree_translator.ex.

For the formatter, we can have a very similar one but much simpler as it requires less information and no validation.

Please let me know if you need any further clarification.

Cheers.

**Comment by paulstatezny** [comment]
@msaraiva What syntax can I write to get the tokenizer to emit a tagged expression?

  * `{:tagged_expr, marker, expr, meta}` - where `marker` can be `...` or `=`

**Comment by paulstatezny** [comment]
Notes to self:

- [ ] `<template name="footer">` -> `<:footer>`
- [ ] `:attrs={{@attrs}}` -> `{...@attrs}`
- [ ] Alternative sigil delimiters: https://github.com/surface-ui/surface/blob/master/lib/mix/tasks/surface/convert.ex#L60-L84

**Comment by msaraiva** [comment]
Hey @paulstatezny!

The tokenizer is emitting the tokens just fine as you can see here:

```
iex(1)> Surface.Compiler.Tokenizer.tokenize!("<Component {=@foo} {...@bar}>")
[
  {:tag_open, "Component",
   [
     {:root,
      {:tagged_expr, "=",
       {:expr, "@foo",
        %{column: 14, column_end: 18, file: "nofile", line: 1, line_end: 1}},
       %{column: 13, column_end: 14, file: "nofile", line: 1, line_end: 1}},
      %{column: 12, column_end: 19, file: "nofile", line: 1, line_end: 1}},
     {:root,
      {:tagged_expr, "...",
       {:expr, "@bar",
        %{column: 24, column_end: 28, file: "nofile", line: 1, line_end: 1}},
       %{column: 21, column_end: 24, file: "nofile", line: 1, line_end: 1}},
      %{column: 20, column_end: 29, file: "nofile", line: 1, line_end: 1}}
   ],
   %{
     column: 2,
     ...
   }}
]
```

However, those tokens are later translated by the `Surface.Compiler.ParseTreeTranslator` to generate the tree in the format expected by the compiler. 

As I mentioned a while ago, you'll  probably have to implement your own node translator so you can have full control on the final generated tree. To do that, you just have to implement the `Surface.Compiler.NodeTranslator` behaviour.

You can start by simply copying the implementation of the default [Surface.Compiler.ParseTreeTranslator](https://github.com/surface-ui/surface/blob/master/lib/surface/compiler/parse_tree_translator.ex) and change the translation of the tagged expressions like in https://github.com/surface-ui/surface/blob/master/lib/surface/compiler/parse_tree_translator.ex#L126-L148.

Your implementation will be even simpler than that since the formatter requires much less information than the compiler. For instance, you don't care if the tag represents a component or an HTML tag, so you can emit a much simpler node.

You can also remove all the validation if you want. After all, the formatter should only run on an already successfully built project.

**Comment by paulstatezny** [comment]
Ah, that makes complete sense. I understand now. 🙂

I'll wait until some time after 0.5 is launched to make SurfaceFormatter use a custom NodeTranslator.

**Comment by msaraiva** [comment]
That's great but is it possible to release the formatter for `v0.5` without the custom node translator?

What was the feature you were trying to implement?

**Comment by paulstatezny** [comment]
Definitely! That's what I'm saying -- let's get `v0.5` released first, and I'll consider a custom NodeTranslator some time in the future.

Regarding `:tagged_expr`, I'm not trying to implement a specific feature, just trying to make sure the formatter handles every possible scenario. I thought `parse!` was going to return `:tagged_expr`, but I see with the default NodeTranslator now that it doesn't.

**Comment by paulstatezny** [comment]
Actually, follow-up question about `template` -- should the formatter turn the deprecated `<template slot="foo">` (`template`, not `#template`) into `<:foo>`?

**Comment by paulstatezny** [comment]
#23 merged!
