### ISSUE TITLE
Is it possible to auto-format on save?

### ISSUE THREAD

**Issue by iacobson** [surface-ui/surface_formatter#25]
The extension works great.
I was just wondering if there's an option to automate format on save on VSCode (like the elixir format that runs with elixir-ls).
Would it be possible to have it as an option in the surface [VSCode extension](https://marketplace.visualstudio.com/items?itemName=msaraiva.surface)?

**Comment by alexanderzinolidis** [comment]
If you use VS Code, you can:

1. Install the extension `emeraldwalk.runonsave`
2. In VS Code's `settings.json`, add an entry like this:

```js
"emeraldwalk.runonsave": {
    "commands": [
      {
        "match": "\\.sface|ex?$",
        "isAsync": true,
        "cmd": "cd ${workspaceRoot} && mix surface.format ${file}"
      }
    ]
},
```

It seems to be working fine for me with ElixirLS auto formatting enabled. Not sure if this is prone to some nasty race-conditions since this probably runs at the same time as the standard formatter.

**Comment by iacobson** [comment]
@alexanderzinolidis thanks! 
Works fine for me. 
I did not encounter any issues (race condition) yet. However, seems that the CPU spiles when saving `.ex` files.
I'll see how it goes in during the next days, and worse case I remove the `ex` from `match`. Formatting `.sface` is still a big step.

**Comment by ppiechota** [comment]
Hi all, thanks for a tip regarding runonsave, but as Surface Formatter with its Elixir 1.13 plugin is now part of mix format I expected that it would be run on save in VS Code thanks to ElixirLS extension, but it is not. Is this a case with ElixirLS extension or could it be configured somehow?

**Comment by paulstatezny** [comment]
@ppiechota As formatter plug-ins are specified in `.formatter.exs`, I wonder if ElixirLS is specifying its own `.formatter.exs`? Or perhaps somehow running `Code.format_string!` on its own without calling `mix format`? (Which would require manually passing the `.formatter.exs` options.)

Does anyone know how ElixirLS does this internally?

**Comment by ppiechota** [comment]
@paulstatezny 

https://elixirforum.com/t/introducing-elixirls-the-elixir-language-server/5857/144?u=ppiechota

ElixirLS has just been updated to work with elixir 1.13, I guess it was the issue so far but I can't check it now, I'll do it later today.

**Comment by ppiechota** [comment]
Well... I checked and either the vscode extension is not updated yet or I'm missing something. Let's reach the authors:
https://elixirforum.com/t/introducing-elixirls-the-elixir-language-server/5857/145?u=ppiechota
