### ISSUE TITLE
Formatter changes <template> tags

### ISSUE THREAD

**Issue by lukashambsch** [surface-ui/surface_formatter#30]
Running mix surface.format will change `<template>` to `<#template>`. For me, that change results in a compilation error because it's changing a template tag that I'm using for AlpineJS.

**Comment by paulstatezny** [comment]
Thanks for reporting this, @lukashambsch! Version 0.5.1 was just released, and it patches this behavior so that `<template>` is now left alone.

https://hex.pm/packages/surface_formatter/0.5.1

**Comment by lukashambsch** [comment]
👍 Thanks!
