### ISSUE TITLE
non-self-closable HTML tags are formatted to become self-closed tags

### ISSUE THREAD

**Issue by ndac-todoroki** [surface-ui/surface_formatter#58]
Example:

```html
# this div exists for creating space inside display: flex
<div class="flex-1"></div>
```

is formatted as

```html
<div class="flex-1" />
```

According to the W3C validator, self-closing `div`s are not valid. (https://validator.w3.org/nu/#textarea)
Maybe self-closing should be done only for whitelisted tags?

**Comment by paulstatezny** [comment]
@ndac-todoroki Thanks for opening an issue!

Unless I'm mistaken, **Surface/LiveView will render `<div></div>` if your Surface code is `<div />`.**

Therefore, HTML tags with no contents can be collapsed in Surface code into a single self-closed ("void") element, and they will emit the same exact HTML. This is why the formatter chooses to make those tags self-closing.

**Comment by paulstatezny** [comment]
For reference, here's the test that demonstrates that this is an intentional design choice. (It uses a component, but applies to HTML elements for the reasons described above.)

https://github.com/surface-ui/surface_formatter/blob/v0.7.4/test/surface/formatter_test.exs#L404-L418

**Comment by ndac-todoroki** [comment]
Ah! I was confused between heex files and sface files!
I tested `<div />` inside my sface file now and it indeed render `<div></div>` correctly.
Sorry for the trouble!

**Comment by paulstatezny** [comment]
@ndac-todoroki Excellent! No trouble at all; thank you for raising the issue. Now we've double checked and ruled out that this could be a problem. 🙂
