### ISSUE TITLE
Interoperability with other Formatter Plugins

### ISSUE THREAD

**Issue by maennchen** [surface-ui/surface_formatter#60]
## Input

```
<div>
  {gettext(~M"It's my cat's {year, selectordinal, one {#st} two {#nd} few {#rd} other {#th}} birthday!")}
</div>
```

## Expected

The Formatter Plugin for the `M` sigil is executed. (In this example: https://hexdocs.pm/ex_cldr_messages/Cldr.Formatter.Plugin.html#content)

## `.formatter.exs`

```elixir
[
  inputs: ["..."],
  plugins: [Surface.Formatter.Plugin, Cldr.Formatter.Plugin]
]

```

**Comment by paulstatezny** [comment]
@maennchen This seems like it might be a missing feature in Elixir 1.13's Formatter Plugins. 🤔

Feels odd that it would be the responsibility of a specialized formatter to be aware of other formatters.

**Comment by maennchen** [comment]
@paulstatezny I thought so. Should we raise this with the elixir team?

**Comment by maennchen** [comment]
@paulstatezny If you don't mind and haven't done anything yourself yet, I would propose to send a message to the elixir mailing list. What do you think?

**Comment by maennchen** [comment]
@paulstatezny Sure :) I'll write a message to the mailing list and will mention this issue as well.

**Comment by maennchen** [comment]
@paulstatezny Actually while looking at the code of this lib, I noticed that maybe it already exists. I'll try something first and if it works, I'll open a PR.

Otherwise, I'll write the message.

**Comment by maennchen** [comment]
@paulstatezny Hm. That did unfortunately not work:

https://github.com/surface-ui/surface_formatter/compare/master...jshmrtn:use_formatter_fn?expand=1

I wanted to replace the `Code.format_string!` call with the function returned by `Mix.Tasks.Format.formatter_for_file`.

There's two reasons why it does not work:

* Mix does not tell a formatter plugin the filename of the current file to format
* There's no way to override the plugins to remove the current plugin from the list when calling the formatter function

I'll write a message to the mailing list.

**Comment by maennchen** [comment]
Posted: https://groups.google.com/g/elixir-lang-core/c/jFswzSUjsP4

**Comment by maennchen** [comment]
PR open in Elixir: https://github.com/elixir-lang/elixir/pull/11587

**Comment by paulstatezny** [comment]
@maennchen Looks like your PR was released in the latest Elixir version? https://elixirforum.com/t/elixir-v1-13-3-released/45918/9

I haven't tested, but would you consider this issue resolved?

**Comment by maennchen** [comment]
@paulstatezny Working like a charm :)
